// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Expenses.App.API.Database.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_UserId_Tag : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                                DELETE FROM expenses_app.category_tags;
                                DELETE FROM expenses_app.tags;
                                DELETE FROM expenses_app.categories;
                                """);

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
