// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Expenses.App.API.Database.Migrations.Application
{
    /// <inheritdoc />
    public partial class Edit_Tag_Description : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DELETE FROM expenses_app.categories;
                DELETE FROM expenses_app.tags;
                DELETE FROM expenses_app.category_tags;
                """);

            migrationBuilder.AlterColumn<string>(
                name: "description",
                schema: "expenses_app",
                table: "tags",
                type: "character varying(500)",
                maxLength: 500,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "description",
                schema: "expenses_app",
                table: "tags",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "character varying(500)",
                oldMaxLength: 500,
                oldNullable: true);
        }
    }
}
